### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [4]:
attribute_lst = ["class", "lug_boot", "safety", "persons", "door", "maint", "buying"]
attribute_lst



['class', 'lug_boot', 'safety', 'persons', 'door', 'maint', 'buying']

In [2]:
a = np.array([1,2,3], dtype='int32')
b = 'test'
print(a)
print(b)

[1 2 3]
test


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]
